# Generated by Django 5.0.3 on 2024-06-03 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0002_quote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'managed': True},
        ),
    ]
