# Generated by Django 5.0.3 on 2024-06-07 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0005_users_is_active_alter_users_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userroles',
            name='user',
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
        migrations.AlterModelOptions(
            name='authuser',
            options={'managed': True},
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.DeleteModel(
            name='UserRoles',
        ),
    ]
