# Generated by Django 5.0.3 on 2024-06-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0006_remove_userroles_user_delete_roles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterModelTable(
            name='authuser',
            table='custom_auth_user',
        ),
    ]
