# Generated by Django 5.0.3 on 2024-06-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0007_authuser_phone_number_alter_authuser_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
