# Generated by Django 5.0.3 on 2024-06-07 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0009_alter_authuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authuser',
            options={'managed': False},
        ),
    ]
