# Generated by Django 5.0.3 on 2024-06-07 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0010_alter_authuser_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='authuser',
            table='auth_user',
        ),
    ]
